version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack:/var/lib/localstack
      - ./aws:/etc/localstack/init/ready.d
    ports:
      - 4566:4566
